export const trabajadores = [
  {
    id: 1,
    nombre: "Ana García Herrera",
    puesto: "Gerente General",
    departamento: "Dirección",
    sueldo: 40000,
    turno: "Matutino",
    activo: true,
    fechaIngreso: "2018-03-12",
  },
  {
    id: 2,
    nombre: "Carlos López Mendoza",
    puesto: "Desarrollador Senior",
    departamento: "TI",
    sueldo: 28000,
    turno: "Matutino",
    activo: true,
    fechaIngreso: "2020-07-01",
  },
  {
    id: 3,
    nombre: "María Torres Vega",
    puesto: "Analista Financiero",
    departamento: "Finanzas",
    sueldo: 22000,
    turno: "Matutino",
    activo: false,
    fechaIngreso: "2019-11-20",
  },
  {
    id: 4,
    nombre: "Luis Ramírez Soto",
    puesto: "Diseñador UX",
    departamento: "TI",
    sueldo: 21000,
    turno: "Matutino",
    activo: true,
    fechaIngreso: "2021-02-14",
  },
  {
    id: 5,
    nombre: "Sofía Mendoza Ríos",
    puesto: "Contadora",
    departamento: "Finanzas",
    sueldo: 24000,
    turno: "Matutino",
    activo: true,
    fechaIngreso: "2017-09-05",
  },
  {
    id: 6,
    nombre: "Roberto Jiménez Cruz",
    puesto: "Soporte Técnico",
    departamento: "TI",
    sueldo: 15000,
    turno: "Vespertino",
    activo: true,
    fechaIngreso: "2022-01-10",
  },
  {
    id: 7,
    nombre: "Valentina Ruiz Mora",
    puesto: "Reclutadora",
    departamento: "RH",
    sueldo: 18000,
    turno: "Matutino",
    activo: true,
    fechaIngreso: "2021-06-30",
  },
  {
    id: 8,
    nombre: "Diego Castillo Nuñez",
    puesto: "Vendedor",
    departamento: "Ventas",
    sueldo: 14000,
    turno: "Matutino",
    activo: false,
    fechaIngreso: "2023-03-22",
  },
  {
    id: 9,
    nombre: "Paola Flores Aguilar",
    puesto: "Coordinadora de RH",
    departamento: "RH",
    sueldo: 26000,
    turno: "Matutino",
    activo: true,
    fechaIngreso: "2016-08-18",
  },
  {
    id: 10,
    nombre: "Miguel Ángel Vargas",
    puesto: "DevOps",
    departamento: "TI",
    sueldo: 32000,
    turno: "Matutino",
    activo: true,
    fechaIngreso: "2020-04-03",
  },
  {
    id: 11,
    nombre: "Isabella Moreno Lara",
    puesto: "Ejecutiva de Ventas",
    departamento: "Ventas",
    sueldo: 16500,
    turno: "Vespertino",
    activo: true,
    fechaIngreso: "2022-09-15",
  },
  {
    id: 12,
    nombre: "Alejandro Peña Domínguez",
    puesto: "Auditor",
    departamento: "Finanzas",
    sueldo: 27000,
    turno: "Matutino",
    activo: true,
    fechaIngreso: "2019-05-07",
  },
  {
    id: 13,
    nombre: "Natalia Ortiz Fuentes",
    puesto: "Community Manager",
    departamento: "Marketing",
    sueldo: 17000,
    turno: "Matutino",
    activo: true,
    fechaIngreso: "2023-01-09",
  },
  {
    id: 14,
    nombre: "Fernando Reyes Blanco",
    puesto: "Jefe de Almacén",
    departamento: "Operaciones",
    sueldo: 19000,
    turno: "Nocturno",
    activo: false,
    fechaIngreso: "2018-12-01",
  },
  {
    id: 15,
    nombre: "Camila Gutiérrez Pérez",
    puesto: "Diseñadora Gráfica",
    departamento: "Marketing",
    sueldo: 18500,
    turno: "Matutino",
    activo: true,
    fechaIngreso: "2021-11-25",
  },
  {
    id: 16,
    nombre: "Héctor Morales Luna",
    puesto: "Desarrollador Junior",
    departamento: "TI",
    sueldo: 16000,
    turno: "Matutino",
    activo: true,
    fechaIngreso: "2023-07-17",
  },
  {
    id: 17,
    nombre: "Gabriela Salinas Torres",
    puesto: "Supervisora",
    departamento: "Operaciones",
    sueldo: 23000,
    turno: "Vespertino",
    activo: true,
    fechaIngreso: "2017-04-22",
  },
  {
    id: 18,
    nombre: "Andrés Medina Espinoza",
    puesto: "Analista de Datos",
    departamento: "TI",
    sueldo: 25000,
    turno: "Matutino",
    activo: true,
    fechaIngreso: "2020-10-08",
  },
  {
    id: 19,
    nombre: "Lucía Cervantes Ibarra",
    puesto: "Asistente Dirección",
    departamento: "Dirección",
    sueldo: 20000,
    turno: "Matutino",
    activo: true,
    fechaIngreso: "2019-02-13",
  },
  {
    id: 20,
    nombre: "Javier Delgado Montes",
    puesto: "Chofer",
    departamento: "Operaciones",
    sueldo: 12000,
    turno: "Nocturno",
    activo: false,
    fechaIngreso: "2022-06-01",
  },
  {
    id: 21,
    nombre: "Colaf Corronado Nortiega",
    puesto: "Chofer",
    departamento: "Operaciones",
    sueldo: 120000,
    turno: "Nocturno",
    activo: true,
    fechaIngreso: "2020-06-01",
  },
];

// Catálogos auxiliares — útiles para llenar <select> en tus formularios
export const departamentos = [
  "Dirección",
  "TI",
  "Finanzas",
  "RH",
  "Ventas",
  "Marketing",
  "Operaciones",
];
export const puestos = [...new Set(trabajadores.map((t) => t.puesto))].sort();
export const shifts = ["Matutino", "Vespertino", "Nocturno"];
